### PR TITLE
Add a save() method in TextPage, which knows to save in the same charset as was received in the response.

### PR DESCRIPTION
**Pull request by lestephane**

### CODE REVIEW

**Comment by rbri** [comment]
Will be great if you can add a unit test also.

**Comment by lestephane** [comment]
That will take a bit longer, but I guess there's no hurry anyway

**Comment by rbri** [comment]
Have written a simple test and merged your pr.
Many thanks, hope HtmlUnit is some help for you.

**Comment by lestephane** [comment]
Thanks, I used HtmlUnit a long, long time ago, and it's grown by leaps and bounds since then. I'm glad I can give it another try

**Pull request merged**
