### PR TITLE
New test showing HtmlUnit producing different XML-XSLT results vs browser

### PR DESCRIPTION
**Pull request by manstis**

### CODE REVIEW

**Comment by manstis** [comment]
Hi @rbri further to https://github.com/HtmlUnit/htmlunit/issues/118

Here's a new test demonstrating HtmlUnits results vs Chrome. I ran this with:
```
browsers=hu,chrome
chrome.bin=path/to/chromedriver
```
"Real Chrome" shows the XML formatted (indented) whereas all HU results are on a single line.

I hope this helps.

**Comment by rbri** [comment]
Can you please add your name and maybe the email to the list of contributors in the pom.

**Comment by manstis** [comment]
Done in new commit.

**Comment by rbri** [comment]
Thanks
Have done some research on this, looks like only chrome supports this. Also the Java transformer API seems to be a pice of crap. Have to think a bit more about this, but I have an idea of an hack to get all this working. Please be a bit patient.

**Comment by manstis** [comment]
Cool, thanks @rbri.

I _guess_ you could add a `BrowserVersionFeatures` for CHROME/XML_FORMATTING and have your `XMLSerialiser` behave like Chrome.. I think my talk of the underlying Xalan processing is a red-herring and Chrome is simply doing some default formatting (for no reason other than whoever thought it'd be nicer to have the `String` formatted!)... obviously it's your call...

**Comment by rbri** [comment]
Implemented - will inform via twitter if a new snapshot is there

**Pull request closed without merging**
