### PR TITLE
fix: loadJavaScriptFromUrl with scriptCharset

### PR DESCRIPTION
**Pull request by leeyazhou**

### CODE REVIEW

**Comment by rbri** [comment]
Many thanks for this

any chance to add a unit test?

**Comment by rbri** [comment]
have spend some time to try to build a test case for this. Can you please provide a more detailed description about your case (the script tag that triggers this request)

**Comment by leeyazhou** [comment]
> have spend some time to try to build a test case for this. Can you please provide a more detailed description about your case (the script tag that triggers this request)

it happens when the the uri include Chinese, cause it use the default Charset "ISO-8859-1".

**Comment by rbri** [comment]
Ok, found a test case for this and merge is done.
Many thanks.

For the list of contributors and the @author tag in the source code i need your real name. Can you please add a comment with your real name here.

**Comment by rbri** [comment]
also see https://twitter.com/htmlunit :-)

**Pull request merged**
