### PR TITLE
added new set and get for ssl context

### PR DESCRIPTION
**Pull request by alexvrv**
This is what I needed in #623 and #684 

@rbri is there any chance that this can be merged and maybe released soon? Pretty please

### CODE REVIEW

**Comment by rbri** [comment]
Sorry for being not that responsive during the last days - was on a workshop and will be out for two more weeks to have a holiday break. Afterwards we can work together to get this finally done.

**Comment by alexvrv** [comment]
I hope your vacation went well!
Any chance that this can be included in a release this weekend?

**Comment by rbri** [comment]
Hi @alexvrv,
back from vacation and the stack of work is still on my desk ;-).

Had a first look at your PR; made a small code change to always work with the sslcontext internally.

I think the sslContext should be the most important option. If this is set than we have to ignore the others and use the provided one. If not set we can fall back to the current impl. I guess this provides more flexibility.

@alexvrv what do you think?

**Comment by alexvrv** [comment]
Perfect!

**Comment by alexvrv** [comment]
@rbri  Any ETA for a new release with this change? :D

**Comment by alexvrv** [comment]
@rbri  Any news? ...

**Comment by rbri** [comment]
@alexvrv  sorry for the silence - it is released...

**Pull request closed without merging**
