### PR TITLE
Directly call logging methods for static strings

### PR DESCRIPTION
**Pull request by csware**
Directly call static logging methods instead of wrapping into  isXXEnabled

### CODE REVIEW

**Comment by rbri** [comment]
Thanks

**Comment by csware** [comment]
@rbri How to run the tests properly? If I just use maven, I see lots of cannot connect to localhost:222 or something.

**Comment by rbri** [comment]
@csware maven is correct ;-)

    mvn test -U -P without-library-and-huge-tests -Dgpg.skip -Djava.awt.headless=true

should run all the basic tests (similar to https://jenkins.wetator.org/job/HtmlUnit%20-%20Headless/)

Please open an(other) issue for your problems. Hopefully this helps to motivate me to write some doc about that thopic.

But for some tests you need some kind of setup in you etc/hosts to support some host names

	127.0.0.1		www.htmlunit-local.com

	127.0.0.1		host1.htmlunit.org
	127.0.0.1		host2.htmlunit.org
	127.0.0.1		htmlunit.org
	127.0.0.1		htmlunit

**Comment by csware** [comment]
It seems to me as if no server is started.

**Comment by rbri** [comment]
strange, works here (as always)

When running 'mvn test' of course i got some output like this
image

But this is expected, because there are also test for error cases.

Usually the summary after all the stack traces is looking like this
image

and in the end most of the tests are passing.

**Pull request merged**
