### PR TITLE
Add native-image support.

### PR DESCRIPTION
**Pull request by xuxiaocheng0201**
#809

### CODE REVIEW

**Comment by xuxiaocheng0201** [comment]
The metadata file should be fine. But in my personal test, I encountered some issues.
It printed `Exception while removing reference.` and blocked on, also the javascripts was not success.
Tomorrow I will continue to search for what went wrong.

**Comment by xuxiaocheng0201** [comment]
For run with `htmlunit-4.3.0`, should remove these [lines](https://github.com/HtmlUnit/htmlunit/pull/815/files#diff-c89054b680f8e19fb89b010cab099abfb9a6dadc823db4b52987f98bfed7853bR1249-R1275)

**Comment by xuxiaocheng0201** [comment]
@rbri There is a cache mistake in [polyfill](https://github.com/HtmlUnit/htmlunit/pull/815/commits/f5ee73a8113aa3420158558e5adc7dec90e2219b). You may fix it in your next commit.

**Comment by rbri** [comment]
@xuxiaocheng0201 have seen this already - it is on my list

**Pull request closed without merging**
