### PR TITLE
Complete URL props

### PR DESCRIPTION
**Pull request by cdalexndr**
Added missing URL props according to: https://developer.mozilla.org/en-US/docs/Web/API/URL

### CODE REVIEW

**Comment by rbri** [comment]
Can you please add a test for toJSON

**Comment by cdalexndr** [comment]
done

**Comment by rbri** [comment]
Thanks, will include this tomorrow

**Comment by rbri** [comment]
thanks for this contribution

**Comment by rbri** [comment]
waht is your real name - i like to add it to the list of contributors

**Comment by cdalexndr** [comment]
just use my github nickname, it's ok

**Comment by rbri** [comment]
ok, done

Have merged this one and done some minor changes.
It will be great if you can
* create another pr
* add more test at least for some border cases
* run your new test with real browsers to get the expected results (see the javadoc for WebDriverTestCase for details how to to that - and ask if you have some problems)
* maybe you can have a look at the implementation of the similar methods in class HTMLAnchorElement - maybe there are also some tests missing and maybe we can streamline the implementation

Thanks a lot for you PR - hope you will provide more in the future.

**Comment by cdalexndr** [comment]
I've only tested how Firefox handles the border cases from tests. Tests already have _some_ border cases.

**Pull request merged**
