### PR TITLE
Refine the console.log() output of Promise object 

### PR DESCRIPTION
**Pull request by RuralHunter**
Make it similar with Chrome, like this:
```
Promise { <state>: xxx, <value>: xxx }
```

### CODE REVIEW

**Comment by rbri** [comment]
Have implemented this in a slightly different way because i do no like to make the value available from the outside only for this log. Hope this is ok for you.

Thanks for the patch.

**Comment by RuralHunter** [comment]
Thanks, that's better.

**Comment by rbri** [comment]
Just made a new snapshot build and currently working on your constructor issue - looks like a more general problem with all the constructor properties. Hope i can write some tests today and fix it before the weekend. The plan is to make a release this weekend.

**Comment by RuralHunter** [comment]
Great, thanks a lot!

**Pull request closed without merging**
