### PR TITLE
HtmlUnitNekoDOMBuilder: Better handling of <form></form> enclosures

### PR DESCRIPTION
**Pull request by atnak**
This PR contains:
* Fixes to `HtmlUnitNekoDOMBuilder` for better handling of `<form></form>` to fix issues with `<input>` ownership
    * This fixes https://sourceforge.net/p/htmlunit/bugs/1630/
* Refactoring `HtmlUnitNekoDOMBuilder.addNodeToRightParent()` for readability and extensibility

### CODE REVIEW

**Comment by rbri** [comment]
@atnak still a draft or can i merge this?

**Comment by atnak** [comment]
Oh wait I just resumed this today. I'm making tests atm

**Comment by atnak** [comment]
@rbri Thanks for the wait, this PR is ready for review / merge now.

**Comment by rbri** [comment]
Many thanks - as always.
Have merged this and will have a look during the next days.

**Comment by rbri** [comment]
MalformedHtmlTest now shows some problem - i'm already working on this.

**Comment by rbri** [comment]
Hope we catch them all - thanks again.

**Pull request merged**
